language: csharp
dist: xenial
mono: none
dotnet: 3.1
solution: Rene.Utils.Core.sln

os:
  - linux
  - osx  

# install:
#   - nuget restore Rene.Utils.Core.sln
#   - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Release Rene.Utils.Core.sln
#   - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./tests/Rene.Utils.Core.UnitTest/bin/Release/netcoreapp3.1/Rene.Utils.Core.UnitTest.dll

install:
 - dotnet restore Rene.Utils.Core.sln

script: 
 - dotnet build ./src/Rene.Utils.Core/Rene.Utils.Core.csproj -c Release --no-restore
 - dotnet test ./tests/Rene.Utils.Core.UnitTest/Rene.Utils.Core.UnitTest.csproj --no-restore --verbosity normal
