version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}.{build}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
#deploy:
#- provider: NuGet
#  api_key:
#    secure: e3Pg5P610tCMcMypT4V/y3tbr24VANMDZwj7qTtUsDebZiNDKdsDl6hQbzDRpVvZ
#  skip_symbols: true